export const presetLoaderMap = {
  'near-operation-file': () => import('webql-codegen-near-operation-file-preset'),
  'import-types': () => import('webql-codegen-import-types-preset'),
  'java-apollo-android': () => import('webql-codegen-java-apollo-android'),
};

export const pluginLoaderMap = {
  'jsdoc': () => import('webql-codegen-jsdoc'),
  java: () => import('webql-codegen-java'),
  'java-resolvers': () => import('webql-codegen-java-resolvers'),
  'fragment-matcher': () => import('webql-codegen-fragment-matcher'),
  flow: () => import('webql-codegen-flow'),
  'flow-operations': () => import('webql-codegen-flow-operations'),
  'flow-resolvers': () => import('webql-codegen-flow-resolvers'),
  typescript: () => import('webql-codegen-typescript'),
  'typescript-compatibility': () => import('webql-codegen-typescript-compatibility'),
  'typescript-operations': () => import('webql-codegen-typescript-operations'),
  'typescript-resolvers': () => import('webql-codegen-typescript-resolvers'),
  'typescript-apollo-angular': () => import('webql-codegen-typescript-apollo-angular'),
  'typescript-react-apollo': () => import('webql-codegen-typescript-react-apollo'),
  'typescript-vue-apollo': () => import('webql-codegen-typescript-vue-apollo'),
  'typescript-stencil-apollo': () => import('webql-codegen-typescript-stencil-apollo'),
  'typescript-graphql-files-modules': () => import('webql-codegen-typescript-graphql-files-modules'),
  'typescript-graphql-request': () => import('webql-codegen-typescript-graphql-request'),
  'typescript-generic-sdk': () => import('webql-codegen-typescript-generic-sdk'),
  'typescript-type-graphql': () => import('webql-codegen-typescript-type-graphql'),
  'typescript-mongodb': () => import('webql-codegen-typescript-mongodb'),
  'java-apollo-android': () => import('webql-codegen-java-apollo-android'),
  'c-sharp-operations': () => import('webql-codegen-c-sharp-operations'),
  'c-sharp': () => import('webql-codegen-c-sharp'),
  'typescript-urql': () => import('webql-codegen-typescript-urql'),
  'typed-document-node': () => import('webql-codegen-typed-document-node'),
  add: () => import('webql-codegen-add'),
  time: () => import('webql-codegen-time'),
  introspection: () => import('webql-codegen-introspection'),
  'schema-ast': () => import('webql-codegen-schema-ast'),
};
